### ISSUE TITLE
在macOS上报错

### ISSUE THREAD

**Issue by miku1958** [SakuraLLM/Sakura-13B-Galgame#17]
执行pip  install -r requirements.txt后出现这个错误:

                 
Collecting auto_gptq
  Using cached auto_gptq-0.6.0.tar.gz (120 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9c/p8v9xjqn7x9140vwjrvw05h40000gn/T/pip-install-uw9m1lgv/auto-gptq_6a0c36376d1f453bb52a3efc299e5a97/setup.py", line 60, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by pipixia244** [comment]
请检查是否为N卡，以及是否安装了CUDA。
如果上述条件均满足，可以尝试查看以下文档选择指定版本进行安装。
https://github.com/PanQiWei/AutoGPTQ#quick-installation

如果是纯CPU推理，请使用本仓库的llama-cpp-python后端和gguf模型。

**Comment by miku1958** [comment]
auto_gptq 不支持 macOS

**Comment by pipixia244** [comment]
是的，请使用llama-cpp-python后端，或llama.cpp一键包启动模型。

**Comment by miku1958** [comment]
我把0.9下载后, 传入了完整路径, 并且去掉了--use_gptq_model
python server.py --model_name_or_path /Volumes/GPT/Sakura-13B-Galgame/models/sakura-13b-lnovel-v0.9.0pre2-Q8_0.gguf --trust_remote_code --no-auth

结果它给了我这个错误:
```

Traceback (most recent call last):
  File "/Volumes/GPT/Sakura-13B-Galgame/server.py", line 97, in <module>
    state.init_model(cfg)
  File "/Volumes/GPT/Sakura-13B-Galgame/utils/state.py", line 24, in init_model
    sakura_model = SakuraModel(*args, **kwargs)
  File "/Volumes/GPT/Sakura-13B-Galgame/utils/model.py", line 132, in __init__
    (tokenizer, model) = load_model(cfg)
  File "/Volumes/GPT/Sakura-13B-Galgame/utils/model.py", line 79, in load_model
    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, use_fast=False, trust_remote_code=args.trust_remote_code, use_safetensors=False)
  File "/Volumes/GPT/pythongpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 686, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/Volumes/GPT/pythongpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 519, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/Volumes/GPT/pythongpt/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/Volumes/GPT/pythongpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Volumes/GPT/pythongpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/Volumes/GPT/Sakura-13B-Galgame/models/sakura-13b-lnovel-v0.9.0pre2-Q8_0.gguf'. Use `repo_type` argument if needed.
```

**Comment by miku1958** [comment]
这个model_name_or_path不是这样用的吗

**Comment by pipixia244** [comment]
使用llama-cpp-python后端需要增加启动参数`--llama_cpp`，

（使用autogptq后端则增加`--use_gptq_model`，都不加默认为transformers后端）

如果使用GPU推理，则需再增加启动参数`--use_gpu`

**Comment by miku1958** [comment]
建议更新一下README, 没看到--llama_cpp

**Comment by pipixia244** [comment]
https://github.com/SakuraLLM/Sakura-13B-Galgame#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

readme中的“快速开始”处已标注python版本教程，后续会删除下方过时版本。
