### ISSUE TITLE
[BUG] error parsing empty line in translate_epub.py

### ISSUE THREAD

**Issue by miku1958** [SakuraLLM/Sakura-13B-Galgame#19]
```
Llama.generate: prefix-match hit

llama_print_timings:        load time =   20742.46 ms
llama_print_timings:      sample time =       3.99 ms /    85 runs   (    0.05 ms per token, 21319.29 tokens per second)
llama_print_timings: prompt eval time =    7256.54 ms /   142 tokens (   51.10 ms per token,    19.57 tokens per second)
llama_print_timings:        eval time =    7446.32 ms /    84 runs   (   88.65 ms per token,    11.28 tokens per second)
llama_print_timings:       total time =   14999.55 ms
100%|█████████████████████████████████████████████████████████████████████████| 1/1 [00:15<00:00, 15.00s/it]
	./temp/item/xhtml/p-caution.xhtml translated, used time:  15.002065896987915
	translating ./temp/item/xhtml/p-009.xhtml...
Traceback (most recent call last):
  File "/Volumes/GPT/Sakura-13B-Galgame/translate_epub.py", line 271, in <module>
    main()
  File "/Volumes/GPT/Sakura-13B-Galgame/translate_epub.py", line 220, in main
    data_list, file_text = get_html_text_list(html_path, args.text_length)
  File "/Volumes/GPT/Sakura-13B-Galgame/translate_epub.py", line 50, in get_html_text_list
    pre_end = groups[-1].end()
IndexError: list index out of range

```

运行参数
```
python translate_epub.py \
    --model_name_or_path /Volumes/GPT/Sakura-13B-Galgame/models/sakura-13b-lnovel-v0.8-Q5_K_M.gguf \
    --trust_remote_code \
    --model_version 0.8 \
    --llama_cpp \
    --use_gpu \
    --text_length 512 \
    --data_path "転スラ vol.21.epub" \
    --output_folder /Volumes/Temp
```

测试文件: 
[転スラ vol.21.epub.zip](https://github.com/SakuraLLM/Sakura-13B-Galgame/files/13684864/vol.21.epub.zip)

**Comment by pipixia244** [comment]
This may have been solved in #21 .
