### ISSUE TITLE
[Bug] AutoGPTQ后端StreamOutput模式推理报错

### ISSUE THREAD

**Issue by Isotr0py** [SakuraLLM/Sakura-13B-Galgame#30]
使用AutoGPTQ后端进行StreamOutput模式推理时发生报错，且API线程阻塞：
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/SakuraLLM/Sakura-13B-LNovel-v0_8-3bit/b2c35c039738b83cc96558ca6cb8b935ae55c3be/modeling_baichuan.py", line 705, in forward
    logits = self.lm_head(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/SakuraLLM/Sakura-13B-LNovel-v0_8-3bit/b2c35c039738b83cc96558ca6cb8b935ae55c3be/modeling_baichuan.py", line 521, in forward
    return nn.functional.linear(hidden_states, norm_weight)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::Half != float
```
- 复现：部署AutoGPTQ后端，运行`example_openai.py`
- `StreamOutput=False`可正常工作
- llama.cpp后端StreamOutput模式运行正常

**Comment by pipixia244** [comment]
关于线程阻塞：#31 

关于推理报错：
此问题为baichuan2模型的`modeling_baichuan.py`代码问题。
需要将下面的代码
```python
class NormHead(nn.Module):
    def __init__(self, hidden_size, vocab_size, bias=False):
        super().__init__()
        self.weight = nn.Parameter(torch.empty((vocab_size, hidden_size)))
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        self.first_flag = True

    def forward(self, hidden_states):
        if self.training:
            norm_weight = nn.functional.normalize(self.weight)
            self.first_flag = True
        elif self.first_flag:
            self.first_flag = False
            self.weight.data = nn.functional.normalize(self.weight)
            norm_weight = self.weight
        else:
            norm_weight = self.weight
        return nn.functional.linear(hidden_states, norm_weight)
```

改为
```python
class NormHead(nn.Module):
    def __init__(self, hidden_size, vocab_size, bias=False):
        super().__init__()
        self.weight = nn.Parameter(torch.empty((vocab_size, hidden_size)))
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        self.first_flag = True

    def forward(self, hidden_states):
        if self.training:
            norm_weight = nn.functional.normalize(self.weight)
            self.first_flag = True
        elif self.first_flag:
            self.first_flag = False
            self.weight.data = nn.functional.normalize(self.weight)
            norm_weight = self.weight
        else:
            norm_weight = self.weight
        return nn.functional.linear(hidden_states, norm_weightnorm_weight.to(hidden_states.dtype))
```
