### ISSUE TITLE
本地gguf模型路径应该怎么写

### ISSUE THREAD

**Issue by DDXDB** [SakuraLLM/Sakura-13B-Galgame#38]
已经下载了gitattributes和sakura-13b-lnovel-v0.9.0pre3-Q2_K.gguf，放在\models\Sakura-13B-LNovel-v0.9.0pre2-GGUF文件夹里
指令./python server.py --listen "127.0.0.1:5000" --model_name_or_path "Sakura-13B-LNovel-v0.9.0pre2-GGUF" --trust_remote_code --llama_cpp --no-auth
会报错ValueError: Model path does not exist: sakura-13b-lnovel-v0.9.0pre3-Q2_K.gguf

另外题外话，能否支持DirectML以便大部分GPU都可运行

**Comment by pipixia244** [comment]
llama.cpp gguf模型只有单一文件，`--model_name_or_path`需指定到具体文件。

p.s. 0.9.0pre3存在一定的质量下降问题，如在非测试环境下推荐退回pre2版本。

> 另外题外话，能否支持DirectML以便大部分GPU都可运行

这个似乎与我的项目无关，这取决于后端的transformers，autogptq以及llama.cpp是否支持。

**Comment by DDXDB** [comment]
> llama.cpp gguf模型只有单一文件，`--model_name_or_path`需指定到具体文件。
> 
> p.s. 0.9.0pre3存在一定的质量下降问题，如在非测试环境下推荐退回pre2版本。
> 
> > 另外题外话，能否支持DirectML以便大部分GPU都可运行
> 
> 这个似乎与我的项目无关，这取决于后端的transformers，autogptq以及llama.cpp是否支持。

路径是要写相对路径还是绝对路径，用/还是\ 
：）

**Comment by DDXDB** [comment]
使用绝对路径试了一下，会提示缺少qwen模块
我尝试安装qwen提示
`PS D:\Program Files\sakura> pip install qwen
Collecting qwen
  Using cached qwen-0.1.0-py3-none-any.whl.metadata (4.4 kB)
Collecting SentencePiece (from qwen)
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\*\AppData\Local\Programs\Python\Python312\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*\AppData\Local\Temp\pip-build-env-evlww27n\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*\AppData\Local\Temp\pip-build-env-evlww27n\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\*\AppData\Local\Temp\pip-build-env-evlww27n\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\*\AppData\Local\Temp\pip-build-env-evlww27n\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'sentencepiece', '-A', 'x64', '-B', 'build', '-DSPM_ENABLE_SHARED=OFF', '-DCMAKE_INSTALL_PREFIX=build\\root']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by pipixia244** [comment]
> 使用绝对路径试了一下，会提示缺少qwen模块

使用的`llama-cpp-python`版本太老，需更新

**Comment by DDXDB** [comment]
> > 使用绝对路径试了一下，会提示缺少qwen模块
> 
> 使用的`llama-cpp-python`版本太老，需[更新](https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/Python%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B#llama-cpp-python%E5%90%8E%E7%AB%AF)

卸载llama重装后能启动服务器了，但运行以后
`utils.model[30524] ERROR Model output is empty, retrying (1/3)..., This is a very rare situation, please report to devs`

**Comment by pipixia244** [comment]
需要完整log与输入的待翻译文本

**Comment by DDXDB** [comment]
重新安装了一遍+更换8.3模型没有上述报错了
使用指令./python server.py  --listen "127.0.0.1:5000" --model_name_or_path "models/Sakura-13B-LNovel-v0_8-3bit" --trust_remote_code --model_version 0.8 --use_gptq_model --no-auth
会提示我没有N卡

**Comment by pipixia244** [comment]
反馈报错请贴完整的log，不要只说一句“会提示我没有N卡”

以及你的显卡是什么呢

**Comment by DDXDB** [comment]
> 反馈报错请贴完整的log，不要只说一句“会提示我没有N卡”
> 
> 以及你的显卡是什么呢

log路径在哪里，我用Arc A770

**Comment by pipixia244** [comment]
以后请按仓库规定的Issue模板提交Issue，Issue模板里明确要求提供显卡型号。

目前项目不支持也不提供Intel显卡教程。

p.s. 你可以自行去[llama.cpp](https://github.com/ggerganov/llama.cpp)仓库查找相关Issue/Discussion，自行编译CLBlast版本以支持Intel Arc显卡。

**Comment by DDXDB** [comment]
我是按照wiki安装的都是CPU的模块。
没有使用GPU的打算

**Comment by pipixia244** [comment]
> 我是按照wiki安装的都是CPU的模块。 没有使用GPU的打算

本项目中gptq模型默认不支持CPU运行，因为会非常慢。如需要CPU运行请用llama.cpp模型后端。
