### ISSUE TITLE
这个报错看不懂

### ISSUE THREAD

**Issue by lingyezhixing** [SakuraLLM/Sakura-13B-Galgame#4]
(sakuraenv) D:\Sakura-13B-Galgame>python translate_novel.py --model_name_or_path SakuraLLM/Sakura-13B-LNovel-v0_8-4bit --trust_remote_code --model_version 0.8 --use_gptq_model --text_length 512 --data_path re0.txt --output_path data_translated.txt --compare_text
Traceback (most recent call last):
  File "D:\Sakura-13B-Galgame\translate_novel.py", line 1, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
ModuleNotFoundError: No module named 'transformers'

(sakuraenv) D:\Sakura-13B-Galgame>pip install -r requirements.txt
Looking in links: https://download.pytorch.org/whl/cu118/torch_stable.html
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
Collecting transformers==4.33.2
  Using cached transformers-4.33.2-py3-none-any.whl (7.6 MB)
Collecting auto-gptq
  Downloading auto_gptq-0.5.0-cp310-cp310-win_amd64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 3.4 MB/s eta 0:00:00
Collecting sentencepiece
  Using cached sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
Collecting bitsandbytes
  Using cached bitsandbytes-0.41.1-py3-none-any.whl (92.6 MB)
Collecting xformers
  Using cached https://download.pytorch.org/whl/cu118/xformers-0.0.22.post7%2Bcu118-cp310-cp310-win_amd64.whl (97.5 MB)
Collecting huggingface-hub<1.0,>=0.15.1
  Using cached huggingface_hub-0.18.0-py3-none-any.whl (301 kB)
Collecting regex!=2019.12.17
  Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl (269 kB)
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting safetensors>=0.3.1
  Using cached safetensors-0.4.0-cp310-none-win_amd64.whl (277 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Collecting numpy>=1.17
  Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Using cached tokenizers-0.13.3-cp310-cp310-win_amd64.whl (3.5 MB)
Collecting packaging>=20.0
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting fsspec
  Using cached fsspec-2023.10.0-py3-none-any.whl (166 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx
  Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting accelerate>=0.22.0
  Using cached accelerate-0.24.1-py3-none-any.whl (261 kB)
Collecting rouge
  Using cached rouge-1.0.1-py3-none-any.whl (13 kB)
Collecting gekko
  Downloading gekko-1.0.6-py3-none-any.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 154.0 kB/s eta 0:00:00
Collecting datasets
  Using cached datasets-2.14.6-py3-none-any.whl (493 kB)
Collecting peft>=0.5.0
  Downloading peft-0.6.0-py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 1.1 MB/s eta 0:00:00
Collecting psutil
  Using cached psutil-5.9.6-cp37-abi3-win_amd64.whl (252 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyarrow>=8.0.0
  Using cached pyarrow-14.0.0-cp310-cp310-win_amd64.whl (24.6 MB)
Collecting multiprocess
  Using cached multiprocess-0.70.15-py310-none-any.whl (134 kB)
Collecting aiohttp
  Using cached aiohttp-3.8.6-cp310-cp310-win_amd64.whl (325 kB)
Collecting xxhash
  Using cached xxhash-3.4.1-cp310-cp310-win_amd64.whl (29 kB)
Collecting pandas
  Using cached pandas-2.1.2-cp310-cp310-win_amd64.whl (10.7 MB)
Collecting dill<0.3.8,>=0.3.0
  Using cached dill-0.3.7-py3-none-any.whl (115 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp310-cp310-win_amd64.whl (28 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting attrs>=17.3.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.2-cp310-cp310-win_amd64.whl (61 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.0-cp310-cp310-win_amd64.whl (44 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Installing collected packages: tokenizers, sentencepiece, pytz, mpmath, bitsandbytes, xxhash, urllib3, tzdata, typing-extensions, sympy, six, safetensors, regex, pyyaml, psutil, packaging, numpy, networkx, multidict, MarkupSafe, idna, fsspec, frozenlist, filelock, dill, colorama, charset-normalizer, certifi, attrs, async-timeout, yarl, tqdm, rouge, requests, python-dateutil, pyarrow, multiprocess, jinja2, gekko, aiosignal, torch, pandas, huggingface-hub, aiohttp, xformers, transformers, accelerate, peft, datasets, auto-gptq
Successfully installed MarkupSafe-2.1.3 accelerate-0.24.1 aiohttp-3.8.6 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 auto-gptq-0.5.0 bitsandbytes-0.41.1 certifi-2023.7.22 charset-normalizer-3.3.2 colorama-0.4.6 datasets-2.14.6 dill-0.3.7 filelock-3.13.1 frozenlist-1.4.0 fsspec-2023.10.0 gekko-1.0.6 huggingface-hub-0.18.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 multidict-6.0.4 multiprocess-0.70.15 networkx-3.2.1 numpy-1.26.1 packaging-23.2 pandas-2.1.2 peft-0.6.0 psutil-5.9.6 pyarrow-14.0.0 python-dateutil-2.8.2 pytz-2023.3.post1 pyyaml-6.0.1 regex-2023.10.3 requests-2.31.0 rouge-1.0.1 safetensors-0.4.0 sentencepiece-0.1.99 six-1.16.0 sympy-1.12 tokenizers-0.13.3 torch-2.1.0+cu118 tqdm-4.66.1 transformers-4.33.2 typing-extensions-4.8.0 tzdata-2023.3 urllib3-2.0.7 xformers-0.0.22.post7+cu118 xxhash-3.4.1 yarl-1.9.2

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(sakuraenv) D:\Sakura-13B-Galgame>python translate_novel.py --model_name_or_path SakuraLLM/Sakura-13B-LNovel-v0_8-4bit --trust_remote_code --model_version 0.8 --use_gptq_model --text_length 512 --data_path re0.txt --output_path data_translated.txt --compare_text
False

===================================BUG REPORT===================================
D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1184, in _get_module    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\generation\utils.py", line 27, in <module>
    from ..integrations.deepspeed import is_deepspeed_zero3_enabled
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\integrations\__init__.py", line 14, in <module>
    from .bitsandbytes import (
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\integrations\bitsandbytes.py", line 11, in <module>
    import bitsandbytes as bnb
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1184, in _get_module    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\31940\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\modeling_utils.py", line 39, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1174, in __getattr__    module = self._get_module(self._class_to_module[name])
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1186, in _get_module    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Sakura-13B-Galgame\translate_novel.py", line 233, in <module>
    main()
  File "D:\Sakura-13B-Galgame\translate_novel.py", line 171, in main
    from auto_gptq import AutoGPTQForCausalLM
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\auto_gptq\__init__.py", line 2, in <module>
    from .modeling import BaseQuantizeConfig
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\auto_gptq\modeling\__init__.py", line 1, in <module>
    from ._base import BaseGPTQForCausalLM, BaseQuantizeConfig
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\auto_gptq\modeling\_base.py", line 17, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1174, in __getattr__    module = self._get_module(self._class_to_module[name])
  File "D:\Sakura-13B-Galgame\sakuraenv\lib\site-packages\transformers\utils\import_utils.py", line 1186, in _get_module    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by kurikomoe** [comment]
看来 windows 教程之后还是写一个叭。。大部分人还是用 win 的

**Comment by kurikomoe** [comment]
Windows 部署教程已经出了，参见：https://sakura.srpr.moe/
