### ISSUE TITLE
[Bug] translate_novel.py 无法开始翻译，最终错误：TypeError: 'LlamaCpp' object is not callable

### ISSUE THREAD

**Issue by AndyX-Net** [SakuraLLM/Sakura-13B-Galgame#68]
**描述一下Bug**
------
Using fallback chat format: None
translating...
text total words: 16781
  0%|                                                                                           | 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "I:\Sakura-13B-Galgame\translate_novel.py", line 251, in <module>
    main()
  File "I:\Sakura-13B-Galgame\translate_novel.py", line 227, in main
    output = get_model_response(
             ^^^^^^^^^^^^^^^^^^^
  File "I:\Sakura-13B-Galgame\translate_novel.py", line 92, in get_model_response
    output = generate(model, generation_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "I:\Sakura-13B-Galgame\translate_novel.py", line 86, in generate
    output = model(prompt, max_tokens=generation_config.__dict__['max_new_tokens'], temperature=generation_config.__dict__['temperature'], top_p=generation_config.__dict__['top_p'], repeat_penalty=generation_config.__dict__['repetition_penalty'], frequency_penalty=generation_config.__dict__['frequency_penalty'])**
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**TypeError: 'LlamaCpp' object is not callable**

(I:\Sakura-13B-Galgame\installer_files\env) I:\Sakura-13B-Galgame>pip install llamacpp --upgrade
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: llamacpp in i:\sakura-13b-galgame\installer_files\env\lib\site-packages (0.1.14)
------

**复现步骤**
python translate_novel.py --llama_cpp --use_gpu --model_name_or_path K:\sakura-launcher-cublas12-b2465\sakura-13b-lnovel-v0.9b-Q4_K_M.gguf --model_version 0.9 --text_length 512 --data_path e:\test.txt --output_path e:\test_translated.txt --trust_remote_code

**预期结果**
预期应该可以正常翻译

**截图**
![image](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/27819097/f29aa1f8-585f-4340-a6d3-05e9a8c31401)

**版本与参数（重要）**
 - OS: [Windows 11 - 10.0.22621.3155]
 - Python版本 [3.11.8]
 - 是否使用GPU，使用什么GPU. [NVIDIA GeForce 4090/已启用]
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本 [e.g. llama.cpp b1604 cu117]
 - 你使用的模型版本 [sakura-13b-lnovel-v0.9b-Q4_K_M.gguf以及sakura-14b-qwen2beta-v0.9-IQ4_XS.gguf]
 - 如果是模型输出问题，请同时附上模型的解码参数 [未知，因为参照教程使用命令行https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/Python%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B]

**其他信息**
已参照教程[https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/Python%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B配置，目前看起来LLM可以加载但是无法翻译。已经尝试使用git pull同步至最新版。已经检查llamacpp安装为最新版。
似乎卡在了 translate_novel.py 的 generation_config 但无奈我不是Python专家。

请求各位指点下问题出现在哪，感谢。

**Comment by pipixia244** [comment]
确定为bug，马上修复。可先使用git checkout 11e07f9206530060a86bddab1de1d9ab527f0cab退至旧版本使用。

**Comment by AndyX-Net** [comment]
感谢指点，目前退回checkout 11e07f9206530060a86bddab1de1d9ab527f0cab之后确认可以正常工作 (已经加了参数 --llama_cpp --use_gpu但调用的似乎只有CPU)。

![image](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/27819097/fd72c61a-6a41-4a93-a148-279651df16a6)

**Comment by pipixia244** [comment]
> 已经加了参数 --llama_cpp --use_gpu但调用的似乎只有CPU

尝试使用
```
pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/<cuda-version>
```
安装llama-cpp-python，其中<cuda-version>换成你的cuda版本（只能为12.1，12.2，12.3）

**Comment by pipixia244** [comment]
已修复。
