### ISSUE TITLE
[Bug] httpcore.ReadTimeout的问题

### ISSUE THREAD

**Issue by maigeng** [SakuraLLM/Sakura-13B-Galgame#86]
**描述一下Bug**
我用本地的部署包跑的，刚刚还好好的，结果就出现这些错误，我是用1650显卡跑的，前几天还没事情，本来都要跑完了结果提示读取超时
下面是报错提示

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 69, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 254, in __aiter__
  File "httpcore\_async\connection_pool.py", line 367, in __aiter__
  File "httpcore\_async\connection_pool.py", line 363, in __aiter__
  File "httpcore\_async\http11.py", line 349, in __aiter__
  File "httpcore\_async\http11.py", line 341, in __aiter__
  File "httpcore\_async\http11.py", line 210, in _receive_response_body
  File "httpcore\_async\http11.py", line 224, in _receive_event
  File "httpcore\_backends\anyio.py", line 32, in read
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

**Comment by maigeng** [comment]
破案了，是缓存文件的问题，删掉重开就没事了

**Comment by maigeng** [comment]
好吧，发现显存不够用，可以结束提问了
